
import React, { useState } from 'react';
import { generateBusinessStrategy } from '../geminiService';
import Feedback from '../components/Feedback';

const StrategyPlanner: React.FC = () => {
  const [goals, setGoals] = useState('');
  const [loading, setLoading] = useState(false);
  const [strategy, setStrategy] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);

  const handleSubmit = async () => {
    if (!goals) return;
    setLoading(true);
    setSaved(false);
    try {
      const data = await generateBusinessStrategy(goals);
      setStrategy(data);
    } catch (error) {
      console.error(error);
      alert("Strategy ထုတ်ပေးလို့ မရပါဘူး။");
    } finally {
      setLoading(false);
    }
  };

  const executeDownload = () => {
    if (!strategy) return;
    const element = document.createElement("a");
    const header = `================================================\nWITH YOU WEDDING STUDIO - MARKETING ROADMAP\n================================================\nDATE: ${new Date().toLocaleDateString()}\nGOAL: ${goals}\n\n`;
    const footer = `\n\n================================================\nSTRATEGY GENERATED BY AI MARKETING MASTER\nSTAY FOCUSED, STAY PROFESSIONAL.\n================================================`;
    
    const file = new Blob([header + strategy + footer], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = `WithYou_Strategy_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(element);
    element.click();
    setSaved(true);
    setShowConfirm(false);
    setTimeout(() => setSaved(false), 3000);
  };

  return (
    <div className="space-y-8 burmese-text relative">
      <header>
        <h1 className="text-3xl font-bold mb-2">လုပ်ငန်း တိုးချဲ့ရေး အစီအစဉ်</h1>
        <p className="text-slate-400">With You Studio ကို တောင်ကြီးမြို့မှာ နံပါတ် ၁ ဖြစ်လာဖို့ အစီအစဉ်ဆွဲပြီး သိမ်းထားပါ။</p>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
        <div className="lg:col-span-1 space-y-6">
          <div className="bg-slate-800 p-6 rounded-2xl border border-slate-700 shadow-xl">
            <h3 className="text-lg font-bold mb-4">သင့်ရဲ့ ရည်မှန်းချက်</h3>
            <textarea
              value={goals}
              onChange={(e) => setGoals(e.target.value)}
              placeholder="ဥပမာ - လာမယ့် ၃ လအတွင်း တောင်ကြီးမြို့ရဲ့ အအောင်မြင်ဆုံး Studio ဖြစ်လာဖို့..."
              className="w-full h-48 bg-slate-900 border border-slate-700 rounded-xl p-4 text-sm focus:ring-2 focus:ring-amber-500 outline-none transition-all mb-4"
            />
            <button
              onClick={handleSubmit}
              disabled={loading || !goals}
              className="w-full py-4 bg-amber-600 hover:bg-amber-500 disabled:bg-slate-700 rounded-xl font-bold transition-all shadow-lg shadow-amber-900/20"
            >
              {loading ? 'တွက်ချက်နေသည်...' : 'အစီအစဉ် ဆွဲရန်'}
            </button>
          </div>

          <div className="bg-slate-800/50 p-6 rounded-2xl border border-slate-700">
            <h4 className="text-sm font-bold text-slate-400 mb-4 uppercase tracking-wider">ရွေးချယ်စရာများ</h4>
            <div className="space-y-3">
              <button 
                onClick={() => setGoals("တောင်ကြီးမြို့ရှိ Premium Clients များ ပိုမိုရရှိလာစေရန်။")}
                className="w-full text-left text-xs bg-slate-700/50 p-3 rounded-lg hover:bg-amber-500/20 hover:border-amber-500/50 border border-transparent transition-all"
              >
                💎 Premium Branding
              </button>
              <button 
                onClick={() => setGoals("မင်္ဂလာဆောင်ရာသီမှာ ရိုက်ကူးရေး ၁၀ ခုထက်မနည်း ရရှိရန်။")}
                className="w-full text-left text-xs bg-slate-700/50 p-3 rounded-lg hover:bg-amber-500/20 hover:border-amber-500/50 border border-transparent transition-all"
              >
                📅 Wedding Season Growth
              </button>
            </div>
          </div>
        </div>

        <div className="lg:col-span-3">
          {!strategy && !loading && (
            <div className="h-full bg-slate-800/30 border-2 border-dashed border-slate-700 rounded-3xl flex flex-col items-center justify-center p-20 text-center">
              <div className="w-20 h-20 bg-slate-800 rounded-full flex items-center justify-center text-4xl mb-6 shadow-xl">📋</div>
              <p className="text-slate-500 text-lg font-medium">ရည်မှန်းချက်ကို ထည့်သွင်းပြီး အစီအစဉ်ဆွဲလိုက်ပါ။</p>
            </div>
          )}

          {loading && (
            <div className="space-y-6">
              <div className="h-10 w-1/3 bg-slate-800 rounded-lg animate-pulse" />
              <div className="h-[500px] bg-slate-800 rounded-3xl animate-pulse" />
            </div>
          )}

          {strategy && (
            <div className="bg-slate-800 p-8 md:p-12 rounded-3xl border border-slate-700 shadow-2xl relative">
              <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
                <div>
                  <h2 className="text-2xl font-bold text-amber-400 mb-1">With You Studio Strategy</h2>
                  <p className="text-xs text-slate-500">တောင်ကြီးမြို့အတွက် အထူးပြုလုပ်ထားသော Roadmap</p>
                </div>
                <div className="flex gap-3 w-full md:w-auto">
                   <button 
                    onClick={() => setShowConfirm(true)}
                    className={`flex-1 md:flex-none px-6 py-3 rounded-xl font-bold transition-all flex items-center justify-center gap-2 ${saved ? 'bg-green-600 text-white' : 'bg-amber-600 hover:bg-amber-500 text-white shadow-lg shadow-amber-900/30'}`}
                  >
                    {saved ? '✓ သိမ်းဆည်းပြီးပါပြီ' : '📥 သိမ်းထားရန်'}
                  </button>
                  <button 
                    onClick={() => window.print()}
                    className="flex-1 md:flex-none px-6 py-3 bg-slate-700 hover:bg-slate-600 rounded-xl font-bold transition-all no-print"
                  >
                    🖨️ Print
                  </button>
                </div>
              </div>
              
              <div className="bg-slate-950/50 p-8 rounded-2xl border border-slate-700/50 leading-relaxed text-slate-200 burmese-text whitespace-pre-wrap text-sm md:text-base">
                {strategy}
              </div>

              <div className="mt-10 p-6 bg-amber-500/5 border border-amber-500/20 rounded-2xl">
                <div className="flex items-start gap-4">
                  <span className="text-3xl">🔥</span>
                  <div>
                    <h4 className="font-bold text-amber-400 mb-1 text-sm uppercase tracking-widest">Keep Going!</h4>
                    <p className="text-xs text-slate-400">
                      ဒီ Roadmap ကို သေချာလိုက်နာမယ်ဆိုရင် With You Studio ဟာ တောင်ကြီးမှာ အမြန်ဆုံး အောင်မြင်လာမှာပါ။ စိတ်ရှည်လက်ရှည်နဲ့ အကောင်းဆုံး ကြိုးစားလုပ်ကိုင်သွားပါ။
                    </p>
                  </div>
                </div>
              </div>
              
              <Feedback 
                contentId={`strategy-${Date.now()}`} 
                contentType="strategy" 
              />
            </div>
          )}
        </div>
      </div>

      {/* Confirmation Modal */}
      {showConfirm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-slate-900 border border-slate-700 p-8 rounded-3xl shadow-2xl max-w-sm w-full text-center">
            <div className="w-16 h-16 bg-amber-500/10 rounded-full flex items-center justify-center text-3xl mx-auto mb-6">
              💾
            </div>
            <h3 className="text-xl font-bold mb-2">အစီအစဉ် သိမ်းဆည်းမည်</h3>
            <p className="text-slate-400 text-sm mb-8">
              ဒီ Marketing Roadmap ကို သင့်ဖုန်း/ကွန်ပြူတာထဲမှာ .txt ဖိုင်အနေနဲ့ သိမ်းဆည်းမှာ သေချာပါသလား?
            </p>
            <div className="flex gap-4">
              <button 
                onClick={() => setShowConfirm(false)}
                className="flex-1 py-3 bg-slate-800 hover:bg-slate-700 rounded-xl font-bold transition-all"
              >
                မလုပ်တော့ပါ
              </button>
              <button 
                onClick={executeDownload}
                className="flex-1 py-3 bg-amber-600 hover:bg-amber-500 rounded-xl font-bold transition-all text-white"
              >
                သိမ်းမည်
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default StrategyPlanner;
